[theme]
# Força o modo claro (Branco) para todos os usuários
base = "light"

# Cor principal (Botões ativos e detalhes) - Azul elétrico moderno
primaryColor = "#007bff"

# Fundo geral do painel (Branco absoluto)
backgroundColor = "#FFFFFF"

# Fundo dos cards e containers (Cinza bem clarinho para criar relevo)
secondaryBackgroundColor = "#F0F2F6"

# Cor do texto (Cinza escuro para leitura confortável)
textColor = "#262730"

# Fonte
font = "sans serif"

[server]
toolbarMode = "minimal"
